### ISSUE TITLE
Turnstile will not work when logging in

### ISSUE THREAD

**Issue by viperdriver100** [BkrBkr/AuthCaptchaForJoomla#4]
Hi,

I installed Turnstile for Joomla:
https://github.com/SharkyKZ/joomla-turnstile-plugin/releases

1-It will work if I simply do the native thing from Joomla, like "Forgot PW or email
<img width="336" alt="Screenshot 2022-10-08 at 09 57 34" src="https://user-images.githubusercontent.com/9219295/194696842-c177c3b2-a3eb-40f3-9c39-809c5e537765.png">
2- It will not work if I log in from the front end with AuthCaptchaForJoomla enabled. It will end up with the error that there is no valid Captcha. However, this DOES work with captcha or Google re-Captcha
<img width="424" alt="Screenshot 2022-10-08 at 10 01 39" src="https://user-images.githubusercontent.com/9219295/194696981-ca7d0155-fe79-474e-9bcb-c391d269830b.png">
<img width="171" alt="Screenshot 2022-10-08 at 10 02 08" src="https://user-images.githubusercontent.com/9219295/194697006-9b923bec-db6a-43de-80ea-d2bedd61b9c9.png">

I am very happy with your plugin, and I can't do without so I would continue with hCaptcha. However, could you please have a look?

1 - Debug Mode on does not give me anything
2- Error reporting does not help either

**Comment by BkrBkr** [comment]
Thanks for your request. I just merged the changes proposed by @SharkyKZ and published a new release.
Unfortunately I hadn't had time to test your captcha plugin yet. Could you please install the release and give me a feedback, if it already fixes your issue? The new Version can be found in the [release section](https://github.com/BkrBkr/AuthCaptchaForJoomla/releases). It is not deployed via the Joomla Plugin Updates yet.

**Comment by viperdriver100** [comment]
I have replaced the authcaptcha.php file as it was suggested by SharkyKZ. That is working. However, MoreForms from https://morejoomla.com/products/yootheme-builder/more-form will not send the email, although they claim that they solely use whatever is in Joomla by default. That would mean that they would not be the ones causing the issue in their plugin. But I do not know how that exactly works. I reported to MoreJoomla, but they did not respond yet.

**Comment by BkrBkr** [comment]
Thank you for your feedback. As I understand it your intial issue is solved, correct? AuthCaptcha for Joomla is meant to add a captcha to the Login Module/Component (including the admin page) of Joomla. It is not meant to be used with other plugins and will not add a captcha there. Therefor your issue might be related to Turnstyle or MoreForm, but not to this plugin.

**Comment by viperdriver100** [comment]
Ok, I tested with only Turnstile enabled and it failed, so I guess you are right about MoreForms :-)
However, your updated plugin does not work yet.

I try to attach the version that will work for me.

<img width="157" alt="Screenshot 2022-10-10 at 17 45 26" src="https://user-images.githubusercontent.com/9219295/194905312-064b3396-0448-4659-b93c-bf057a6049ee.png">

[authcaptcha.php.zip](https://github.com/BkrBkr/AuthCaptchaForJoomla/files/9747312/authcaptcha.php.zip)

**Comment by BkrBkr** [comment]
Unfortunately the provided file does not work for Joomla 4 with recaptcha. I found out that you can use Turnstile only if you register a domain at cloudflare. This means I can't test it. I made another fix that may address your problem. Would you mind to test it?
[authcaptcha.zip](https://github.com/BkrBkr/AuthCaptchaForJoomla/files/9747853/authcaptcha.zip)

**Comment by viperdriver100** [comment]
This file here works perfectly.
[authcaptcha-modified-10-oct-2022.zip](https://github.com/BkrBkr/AuthCaptchaForJoomla/files/9747867/authcaptcha-modified-10-oct-2022.zip)

You only have to add a domain (free) at Cloudflare. You do not need to buy a domain name.

**Comment by viperdriver100** [comment]
No, I am sorry, your plugin still does not work after the edits

<img width="639" alt="Screenshot 2022-10-10 at 19 33 09" src="https://user-images.githubusercontent.com/9219295/194922944-6af8f020-da28-42a7-b1e3-6e8701cd6d6b.png">

**Comment by BkrBkr** [comment]
Unfortunately I don't have a test environment for Turnstile right now and I wasn't able to detect your problem. Therefore I won't support Turnstile at the moment.

**Comment by viperdriver100** [comment]
The problem has been solved in the attached file. It works. What do you need from me to test it? I an I will provide.

**Comment by BkrBkr** [comment]
The provided file is not working and will not be adapted.
